apiVersion: v1
kind: Service
metadata:
  name: {{ include "coredns.fullname" . }}
  labels:
    {{- include "coredns.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 53
      targetPort: dns
      protocol: UDP
      name: dns
  selector:
    {{- include "coredns.selectorLabels" . | nindent 4 }}
