apiVersion: v1
kind: Service
metadata:
  name: {{ include "coredns.fullname" . }}
  labels:
    {{- include "coredns.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - port: 53
      targetPort: dns
      protocol: UDP
      name: dns
  selector:
    {{- include "coredns.selectorLabels" . | nindent 4 }}
