apiVersion: v2
name: coredns
description: A Helm chart for Kubernetes
type: application
version: 0.2.0
appVersion: "1.10.1"
icon: https://coredns.io/images/CoreDNS_Colour_Horizontal.png
maintainers:
  - name: MickaelCA
    email: mickael@softizy.com
    url: https://www.softizy.com
