# Default values for coredns.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: coredns/coredns
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# -- Zone Files
dnsZones: {}
#  domain.com: |
#    $ORIGIN domain.com.
#    @	60 IN	SOA sns.dns.icann.org. noc.dns.icann.org. (
#    2017042745 ; serial
#    7200       ; refresh (2 hours)
#    3600       ; retry (1 hour)
#    1209600    ; expire (2 weeks)
#    3600       ; minimum (1 hour)
#    )
#
#    www     IN A     127.0.0.1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: ClusterIP
  # -- Service annotations
  annotations: {}
  # -- Set a fixed ClusterIP
  clusterIP: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
