name: kube-linter

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
    branches:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run on yopass
        id: kube-lint-scan
        uses: stackrox/kube-linter-action@v1
        with:
          directory: charts/yopass
          config: .kube-linter.yaml
