name: "Lint PR"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
    branches:
      - 'main'

permissions: {}

jobs:
  semantic-check:
    name: Semantic Pull Request
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check PR commit messages
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\([\w\-\.]+\))?(!)?: ([\w ])+([\s\S]*)'
          flags: "g"
          error: |
            Commits must follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/).
          checkAllCommitMessages: "true"
          excludeTitle: "true"
          excludeDescription: "true"
          accessToken: ${{ secrets.GITHUB_TOKEN }}
